name: Deploy

on:
  push:
    brunches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install dependences
        working-directory: ./functions
        run: npm install
      - name: build functions
        working-directory: ./functions
        run: npm run build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install dependences
        working-directory: ./functions
        run: npm install
      - name: Deploy to Firebase
        working-directory: /
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
