name: Deploy

on:
  push:
    brunches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install dependences
        working-directory: ./functions
        run: npm install
      - name: build functions
        working-directory: ./functions
        run: npm run build
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install dependences
        working-directory: ./functions
        run: npm install
      - name: build functions
        working-directory: ./functions
        run: npm run build
      - name: gen credentials
        working-directory: ./functions
        run: |
          echo '${{ secrets.FIREBASE_ADMIN_CREDENTIAL }}' > credentials.json
      - name: deploy helloWorld
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: helloWorld
          source_dir: functions
          runtime: nodejs12
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: GOOGLE_APPLICATION_CREDENTIALS=credentials.json
      - name: deploy mp4ToHls
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: mp4ToHls
          source_dir: functions
          runtime: nodejs12
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: GOOGLE_APPLICATION_CREDENTIALS=credentials.json
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: rojects/${{ secrets.GCP_PROJECT_ID }}/buckets/performances/videos
      - name: deploy onCreateUser
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: onCreateUser
          source_dir: functions
          runtime: nodejs12
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: GOOGLE_APPLICATION_CREDENTIALS=credentials.json
          event_trigger_type: providers/firebase.auth/eventTypes/user.create
          event_trigger_resource: ${{ secrets.GCP_PROJECT_ID }}